apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fastapi
  name: fastapi
spec:
  containers:
  - image: alijilanidev/cloud-native-fastapi:dev
    name: fastapi 
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
